### ISSUE TITLE
Not working on WordPress 4.0

### ISSUE THREAD

**Issue by shield-9** [grok/wordpress-plugin-scalable-vector-graphics#5]
This plugin is not working on WordPress 4.0-beta4-20140824 with Grid View.

**Comment by Lewiscowles1986** [comment]
https://gist.github.com/Lewiscowles1986/44f059876ec205dd4d27 (a plugin that works) 

& 

https://core.trac.wordpress.org/ticket/31258#comment:10 (the resulting patch for core ;))

**Comment by grok** [comment]
Thanks Lewis!

Mind if I integrate that or a variation of it into this plugin?

**Comment by Lewiscowles1986** [comment]
No problems grok, as you can see, I'm not willing to abandon Git to publish plugins hahaha. WordPress will have to catch up and even then, it's GNU licensed use, modify distribute etc. Thanks for asking, would also be nice to get a mention or something, but not required.

**Comment by grok** [comment]
Of course man! Happy to include your github name and/or wordpress.org name in the commit/readme.

Of course...I need to actually find time to do all the things...

**Comment by grok** [comment]
This is now pushed to github, will roll out to SVN when I get a moment.
