### ISSUE TITLE
Broken on nginx

### ISSUE THREAD

**Issue by theMikeD** [grok/wordpress-plugin-scalable-vector-graphics#6]
I may be wrong here, but I think there is something amiss with nginx. When I drag an svg file into WP Media screen while this plugin is active, the file uploads but then I'm shown an error message:
![screen shot 2015-06-15 at 5 55 24 pm](https://cloud.githubusercontent.com/assets/423907/8171660/b9263a64-1387-11e5-80c0-7191119817eb.png)
...but the file is in fact uploaded, and when I refresh the media screen, the svg file is present.

**Comment by theMikeD** [comment]
Disabling ```public function sanitize_svg``` fixes the issue FTR

**Comment by grok** [comment]
FYI, new path coming down that removes the sanitization stuff. It was a bad idea IMO.
